"use client";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { SparklesIcon, AlertCircle } from "lucide-react";

interface Props {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onAccept: () => void;
}

export function AIDisclaimerDialog({ open, onOpenChange, onAccept }: Props) {
  const handleAccept = () => {
    onAccept();
    onOpenChange(false);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-2xl">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 text-2xl">
            <SparklesIcon className="h-6 w-6 text-primary" />
            Introducing AI Content Generation
            <span className="text-xs bg-blue-100 dark:bg-blue-900 text-blue-600 dark:text-blue-300 px-2 py-1 rounded-full font-normal">
              Beta
            </span>
          </DialogTitle>
          <DialogDescription className="text-base pt-2">
            Hey there, we&apos;re thrilled to present our AI-powered content generation feature.
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 py-4">
          <p className="text-sm text-muted-foreground">
            Simply click the &quot;Write with AI&quot; button, and watch as we generate optimized content for
            your listings, taking into account your product details, selected template, and high-performing
            keywords from your keyword bank.
          </p>

          <p className="text-sm text-center font-medium text-foreground">
            Enjoy optimizing!
          </p>

          <div className="bg-amber-50 dark:bg-amber-950 border border-amber-200 dark:border-amber-800 rounded-lg p-4 space-y-2">
            <div className="flex items-start gap-2">
              <AlertCircle className="h-5 w-5 text-amber-600 dark:text-amber-400 flex-shrink-0 mt-0.5" />
              <div className="space-y-2 text-xs text-amber-900 dark:text-amber-200">
                <p className="font-semibold">Disclaimer:</p>
                <p>
                  While we strive to deliver precise and relevant content, the output generated by our AI is purely
                  automated and may not always be perfect. We strongly recommend reviewing and editing the content
                  generated by our tool before using it for your Amazon listings.
                </p>
                <p className="mt-2">
                  We are not responsible for and do not guarantee any specific results or outcomes from using our
                  auto-generated content. As the seller, you are responsible for the accuracy and legality of your
                  Amazon listings.
                </p>
              </div>
            </div>
          </div>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>
            Cancel
          </Button>
          <Button onClick={handleAccept} className="gap-2">
            <SparklesIcon className="h-4 w-4" />
            Acknowledge & Continue
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
